/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/

/* ---BookingEntity--- */

export interface BookingEntity {
    Row: {
        'createdAt'?: Date;
        'endTime': Date;
        'id': string;
        'maintainerId': string;
        'startTime': Date;
        'status'?: BookingStatus;
        'totalAmount': number;
        'updatedAt': Date;
        'userProfileId': string;
    };
    Insert: {
        'createdAt'?: Date;
        'endTime': Date;
        'id': string;
        'maintainerId': string;
        'startTime': Date;
        'status'?: BookingStatus;
        'totalAmount': number;
        'updatedAt': Date;
        'userProfileId': string;
    };
    Update: {
        'createdAt'?: Date;
        'endTime': Date;
        'id': string;
        'maintainerId': string;
        'startTime': Date;
        'status'?: BookingStatus;
        'totalAmount': number;
        'updatedAt': Date;
        'userProfileId': string;
    };
}



/* ---MaintainerProfileEntity--- */

export interface MaintainerProfileEntity {
    Row: {
        'availability': string;
        'createdAt'?: Date;
        'expertise'?: string[] | null;
        'githubProfile'?: string | null;
        'hourlyRate': number;
        'id': string;
        'projectId': string;
        'updatedAt': Date;
        'userProfileId': string;
    };
    Insert: {
        'availability': string;
        'createdAt'?: Date;
        'expertise'?: string[] | null;
        'githubProfile'?: string | null;
        'hourlyRate': number;
        'id': string;
        'projectId': string;
        'updatedAt': Date;
        'userProfileId': string;
    };
    Update: {
        'availability': string;
        'createdAt'?: Date;
        'expertise'?: string[] | null;
        'githubProfile'?: string | null;
        'hourlyRate': number;
        'id': string;
        'projectId': string;
        'updatedAt': Date;
        'userProfileId': string;
    };
}



/* ---ProjectEntity--- */

export interface ProjectEntity {
    Row: {
        'createdAt'?: Date;
        'description'?: string | null;
        'id': string;
        'name': string;
        'repoUrl': string;
        'updatedAt': Date;
    };
    Insert: {
        'createdAt'?: Date;
        'description'?: string | null;
        'id': string;
        'name': string;
        'repoUrl': string;
        'updatedAt': Date;
    };
    Update: {
        'createdAt'?: Date;
        'description'?: string | null;
        'id': string;
        'name': string;
        'repoUrl': string;
        'updatedAt': Date;
    };
}



/* ---UserEntity--- */

export interface UserEntity {
    Row: {
        'id': string;
    };
    Insert: {
        'id': string;
    };
    Update: {
        'id': string;
    };
}



/* ---UserProfileEntity--- */

export interface UserProfileEntity {
    Row: {
        'createdAt'?: Date;
        'email': string;
        'id': string;
        'name': string;
        'updatedAt': Date;
    };
    Insert: {
        'createdAt'?: Date;
        'email': string;
        'id': string;
        'name': string;
        'updatedAt': Date;
    };
    Update: {
        'createdAt'?: Date;
        'email': string;
        'id': string;
        'name': string;
        'updatedAt': Date;
    };
}


export enum BookingStatus {
  'CANCELLED' = 'CANCELLED',
  'COMPLETED' = 'COMPLETED',
  'CONFIRMED' = 'CONFIRMED',
  'PENDING' = 'PENDING',
}
